version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: database
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  adminer:
    image: adminer
    ports:
      - "9802:8080"

  web:
    image: nginx:latest
    ports:
      - "9800:81"
    volumes:
      - ./web:/var/www/html
      - ./site-web.conf:/etc/nginx/conf.d/site.conf

  redis:
    image: redis:latest

  php:
    build: ./api
    volumes:
      - ./api:/var/www/html
    links:
      - redis
      - db

  api:
    image: nginx:latest
    ports:
      - "9801:81"
    volumes:
      - ./api:/var/www/html
      - ./site-api.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - redis

